Controllers films users
Daimand1997/filmorate-java pull request #2
Opened 2023-12-28 13:25 UTC by Daimand1997

2023-12-29 14:29 UTC, db-exp requested changes

2023-12-29 14:29 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Релизная дата формата yyyy-mm-dd не может быть пустой")
можно Size сразу ставить

2023-12-29 14:29 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Название фильма не может быть пустым")
можно Size сразу ставить

2023-12-29 14:29 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull
и notnull и notempty не нужно - notempty не нужно

2023-12-29 14:29 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/handlers/BussinesExceptionHandler.java
> +public class BussinesExceptionHandler {
в пустом классе особо смысла нет)

2023-12-29 14:29 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServicesImpl.java
> +        if (films.stream().anyMatch(g -> g.equals(film))) throw new ValidationException("The film was created earlier");
лучше Map использовать, а не список

2023-12-29 19:15 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull
Поправил

2023-12-29 19:17 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Название фильма не может быть пустым")
Поправил

2023-12-29 19:18 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/handlers/BussinesExceptionHandler.java
> +public class BussinesExceptionHandler {
Убрал

2023-12-29 19:38 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServicesImpl.java
> +        if (films.stream().anyMatch(g -> g.equals(film))) throw new ValidationException("The film was created earlier");
Переписал

2023-12-29 20:37 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Релизная дата формата yyyy-mm-dd не может быть пустой")
Поправил

2023-12-29 20:37 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServicesImpl.java
> +        if (films.stream().anyMatch(g -> g.equals(film))) throw new ValidationException("The film was created earlier");
Автотесты ждут list

2023-12-30 19:45 UTC, db-exp requested changes

2023-12-30 19:45 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServicesImpl.java
> +        if (films.stream().anyMatch(g -> g.equals(film))) throw new ValidationException("The film was created earlier");
так  у map values(), перебирать список дороже и дольше, чем достать фильм по ключу
Переделай, пожалуйста, в следующем спринте

2023-12-30 19:45 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/UserServicesImpl.java
> +        if (users.stream().anyMatch(g -> g.equals(user))) throw new ValidationException("The user was created earlier");
по аналогии с фильмами - жду правку на map в следующем спринте

2023-12-30 19:45 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotNull(message = "Поле 'login' не может быть пустым или состоять только из пробелов")
NotNull не проверяет пробелы - NotBlank поможет

2023-12-31 00:50 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/service/impl/FilmServicesImpl.java
> +        if (films.stream().anyMatch(g -> g.equals(film))) throw new ValidationException("The film was created earlier");
Понял, переписал

2024-01-01 20:31 UTC, db-exp approved these changes

2024-01-01 20:31 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "Поле 'login' не может быть пустым или состоять только из пробелов")
можно Size докинуть

2024-01-01 21:08 UTC, Daimand1997 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank(message = "Поле 'login' не может быть пустым или состоять только из пробелов")
Докинул

2024-01-01 21:17 UTC, merged